repos:
  - repo: local
    hooks:
      - id: maven-test
        name: maven test
        entry: bash -c './mvnw test && git add target/surefire-reports/'
        language: system
        pass_filenames: false
